micronaut:
  application:
    name: mnQuickstart
  server:
    port: ${SERVER_PORT:8081}
hello:
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hallo Welt"
      en: "Hello World"
